In [26]:
import pandas as pd

df = pd.read_csv('ecommerce_dataset.csv', names=["category", "description"], header=None)
print(df.shape)

(50425, 2)

In [27]:
df.head(3)

    category                                        description
0  Household  Paper Plane Design Framed Wall Hanging Motivat...
1  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  Household  SAF 'UV Textured Modern Art Print Framed' Pain...

In [28]:
df.dropna(inplace=True)
df.shape

(50424, 2)

In [29]:
df.category.unique()

<StringArray>
['Household', 'Books', 'Clothing & Accessories', 'Electronics']
Length: 4, dtype: str

In [36]:
df['category'] = df['category'].replace("Clothing & Accessories", "Clothing_Accessories")

In [38]:
df.category.unique()

<StringArray>
['Household', 'Books', 'Clothing_Accessories', 'Electronics']
Length: 4, dtype: str

In [39]:
df['category'] = '__label__'+df['category'].astype(str)
df.head()

             category                                        description
0  __label__Household  Paper Plane Design Framed Wall Hanging Motivat...
1  __label__Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  __label__Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3  __label__Household  SAF Flower Print Framed Painting (Synthetic, 1...
4  __label__Household  Incredible Gifts India Wooden Happy Birthday U...

In [40]:
df['category_description'] = df['category'] + ' ' + df['description']
df.head()

,category,description,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__Household Paper Plane Design Framed W...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__Household SAF 'Floral' Framed Paintin...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__Household SAF 'UV Textured Modern Art...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__Household SAF Flower Print Framed Pai...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__Household Incredible Gifts India Wood...

In [42]:
import re

text = "  VIKI's | Bookcase/Bookshelf (3-Shelf/Shelve, White) | ? . hi"
text = re.sub(r'[^\w\s\']',' ',text)
text = re.sub(' +',' ',text)
text.strip().lower()

"viki's bookcase bookshelf 3 shelf shelve white hi"

In [43]:
def preprocess(text):
    text = re.sub(r'[^\w\s\']',' ',text)
    text = re.sub(' +',' ',text)
    return text.strip().lower()

In [44]:
df['category_description'] = df['category_description'].map(preprocess)
df.head()

,category,description,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__household paper plane design framed w...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__household saf 'floral' framed paintin...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__household saf 'uv textured modern art...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__household saf flower print framed pai...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__household incredible gifts india wood...

In [47]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [48]:
train.shape, test.shape

((40339, 3), (10085, 3))

In [49]:
train.to_csv("ecommerce.train", columns=["category_description"], index=False, header=False)
test.to_csv("ecommerce.test", columns=["category_description"], index=False, header=False)

In [10]:
import fasttext

model = fasttext.train_supervised(input="ecommerce.train")
model.test("ecommerce.test")

Read 4M words
Number of words:  79329
Number of labels: 4
Progress: 100.0% words/sec/thread: 2992164 lr:  0.000000 avg.loss:  0.218061 ETA:   0h 0m 0s

(10084, 0.9700515668385561, 0.9700515668385561)

In [3]:
model.predict("wintech assemble desktop pc cpu 500 gb sata hdd 4 gb ram intel c2d processor 3")

(('__label__electronics',), array([0.99567312]))

In [4]:
model.predict("ockey men's cotton t shirt fabric details 80 cotton 20 polyester super combed cotton rich fabric")

(('__label__clothing_accessories',), array([1.00001001]))

In [5]:
model.predict("think and grow rich deluxe edition")

(('__label__books',), array([1.00000989]))

In [6]:
model.get_nearest_neighbors("painting")

[(0.9987660050392151, 'ragout'),
 (0.9987660050392151, 'eighths'),
 (0.998740553855896, 'yozo'),
 (0.9987090826034546, 'ragistered'),
 (0.998705267906189, 'metallo'),
 (0.9986783862113953, 'snowbird'),
 (0.9986783862113953, 'kungfu'),
 (0.9986734390258789, 'componentsnegative'),
 (0.9986734390258789, 'thermistors'),
 (0.9986734390258789, 'b3950temperature')]

In [7]:
model.get_nearest_neighbors("sony")

[(0.9991632103919983, 'uncoloured'),
 (0.9991204142570496, 'ap07'),
 (0.9991204142570496, 'crunched'),
 (0.9991204142570496, 'unparalled'),
 (0.9991203546524048, 'celestech'),
 (0.9991104602813721, 'accesory'),
 (0.9991104602813721, 'campatible'),
 (0.9989917278289795, 'demodulated'),
 (0.9989917278289795, 'miniaturized'),
 (0.9989917278289795, 'bmes')]

In [10]:
model.get_nearest_neighbors("samsung")

[(0.9971060156822205, 'power'),
 (0.9936769604682922, 'stand'),
 (0.9926144480705261, 'control'),
 (0.9925626516342163, 'battery'),
 (0.9919418692588806, 'surface'),
 (0.988232433795929, 'creative'),
 (0.9875389337539673, 'allows'),
 (0.9868486523628235, 'tech'),
 (0.9864967465400696, 'office'),
 (0.985217273235321, 'number')]